# Generated by Django 4.1.5 on 2023-01-26 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('address_line_1', models.CharField(max_length=100, null=True)),
                ('address_line_2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('contact_name', models.CharField(max_length=50, null=True)),
                ('contact_no', models.CharField(max_length=20, null=True)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('quantity', models.IntegerField(default=1)),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submit_po.purchaseorder')),
            ],
        ),
    ]
