# Generated by Django 4.1.5 on 2023-01-26 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_name', models.TextField()),
                ('item_description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchaseorderreport',
            fields=[
                ('PO_id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('finance_id', models.IntegerField(default='')),
                ('PO_date', models.DateField()),
                ('PO_tprice', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('quote_id', models.IntegerField(primary_key=True, serialize=False)),
                ('salesstaff_id', models.IntegerField()),
                ('cust_id', models.IntegerField()),
                ('pr_id', models.IntegerField()),
                ('quot_date', models.DateField()),
                ('quo_tprice', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=255)),
                ('qitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ms_app.item')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('purchase_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('pr_date', models.DateField()),
                ('pitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ms_app.item')),
            ],
        ),
    ]
